default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('PG_HOSTNAME') { 'localhost' } %>
  username: <%= ENV.fetch('PG_USR') { 'postgres' } %>
  password: <%= ENV.fetch('PG_PWD') { 'Abc12345678' } %>
  pool: <%= Integer(ENV.fetch('DB_POOL') { 5 }) %>
  timeout: 5000

development:
  <<: *default
  database: alice_in_stars_api_development

test:
  <<: *default
  database: alice_in_stars_api_test

production:
  url: <%= ENV.fetch('DATABASE_URL') { 'localhost' } %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
